language: cpp
dist: bionic
compiler: gcc
install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script: 
  - cd sources/problem4_median && make
  - cd sources/problem7_train && make
