language: cpp
dist: bionic
compiler: gcc
cache: pip
install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script: 
  - g++ ./sources/train_time.cpp -std=c++17 -o travis_gcc_cpp17
  - ./travis_gcc_cpp17 
  - g++ ./sources/median.cpp -std=c++17 -o travis_gcc_cpp17
  - ./travis_gcc_cpp17 
